name: project_g1o
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
<<<<<<< HEAD
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  geolocator: ^11.0.1
=======
  isar: ^3.1.0  
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  geolocator: ^11.0.1  
>>>>>>> a0012ab (add chat_message model and isar dependencies)
  dio: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: any
<<<<<<< HEAD
=======

>>>>>>> a0012ab (add chat_message model and isar dependencies)